### ISSUE TITLE
Demo with dynamic routing ?

### ISSUE THREAD

**Issue by Rambobafet** [47ng/next-usequerystate#282] opened 2022-02-02 14:36 UTC
Hello,

I'm currently having an issue with useQueryState when used in complement of a dynamic routing. I might be missing something but couldn't find information in the doc :x 

I've got something like : 'pages/product/[slug]/[[...params]]' and I'd like to keep some detail about my product in the URL (variant, size...) but as soon as I set a value I get this error :

> Unhandled Runtime Error
Error: The provided `href` (/product/[slug]/[[...params]]?variant=od) value is missing query values (slug, params) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed

I use the version 1.6.0 of next-useQueryState.

Any ideas?

Thanks,
Bobu

**Comment by franky47** [comment] 2022-02-02 14:43
Thanks for the report, that's a bug indeed.

It looks like we're missing the `query` part of the router when calling `router.push|replace`, which does this interpolation of dynamic URL params. Though we're using the `asPath` which is fully interpolated already 🤔 

Ideally, we should only touch the querystring (the `search` property in the router arguments) and leave the rest as-is, but this could require having the router as a dependency in the useCallback for the state update function, which would make it lose its referential stability.

Would you like to open a PR?

**Comment by franky47** [comment] 2022-02-02 15:09
I've published a fix attempt in `1.6.1-beta.1`, could you give it a try and tell me if it solves your problem?

The drawback is that now the state updater function will be recreated when `router.query` changes, so it should not be much of an issue as it usually changes during page transitions, where contents & hooks are unmounted/remounted anyway.

**Comment by Rambobafet** [comment] 2022-02-03 10:45
Hi! Thanks for the quick reply and patch!
Looks good to me, no more errors 🎉

**Comment by franky47** [comment] 2022-02-04 02:22
Hum this fix had a side-effect of no longer allowing to clear the query by setting the state to `null`, I'll look into that before publishing a release.

**Comment by franky47** [comment] 2022-02-04 22:27
Closing as I've got E2E tests that cover this case now. Let me know if you still encounter some issues!

**Comment by franky47** [comment] 2022-02-07 23:57
Reopening as I'm now encountering this issue (but not in E2E tests, maybe not all cases are covered).

We could theoretically use `window.location.pathname` as a replacement for the `asPath` here, if we assume that the query updater function should only work on the query string.

**Comment by SimonProper** [comment] 2023-11-09 14:01
Do we have any updates on this issue? Ran into the same problem as above today when using the hook inside a dynamic route using the pages directory.
Sadly to green on this project to open a PR at the moment, but happy to help if I get some directions on where to start!

**Comment by franky47** [comment] 2023-11-09 14:27
@SimonProper what version of Next.js and next-usequerystate are you using? Are you able to update to 1.8+ (it requires Next.js 13.4+)? The implementation has changed a lot since this issue was (re)opened, and tests with dynamic routes in the pages router seem promising (there is no longer need for the asPath when using `next/navigation`).

**Comment by SimonProper** [comment] 2023-11-09 15:20
@franky47 I did indeed have the wrong version of next, however the problem seems to persists even after updating to next v.14.0.1 and next-usequerystate 1.10.0. I will see if I can make a minimal reproduction example

**Comment by SimonProper** [comment] 2023-11-09 22:35
@franky47  So I managed to reproduce the issue. It is occurring when you are setting a value with the option `shallow:false` inside of a dynamic page. 

Have a look at the codesanbox bellow.
1. click the link to the dynamic route
2. click the button
 
https://codesandbox.io/p/sandbox/next-usequerystate-dynamic-page-issue-79zgvw

**Closed** 2023-11-10 14:00 UTC
Labels: bug, released, released on @beta

**Comment by franky47** [comment] 2023-11-10 14:02
@SimonProper could you try `1.10.2-beta.1` and tell me if it works out for you?

**Comment by SimonProper** [comment] 2023-11-10 20:41
@franky47 I can confirm that it works with your latest changes in `1.10.2-beta-1`. Nice work!
Forked the reproduction and updated the version if you want to test out for yourself: 
https://codesandbox.io/p/sandbox/next-usequerystate-dynamic-page-issue-1-10-2-beta-1-vmmfp2
